baseURL = "/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-US"
metaDataFormat = "yaml"
paginate = 25

[outputs]
home = ["HTML", "RSS"]

[params]
brand = "Health IT Briefing"
description = "Netspective Media Health IT Briefing"

[permalinks]
post = "/post/:year/:month/:day/:slug/"